### ISSUE TITLE
Reading options fails when using a logging library

### ISSUE THREAD

**Issue by nipkownix** [ThirteenAG/IniReader#1]
First encountered the issue here: https://github.com/nipkownix/re4_tweaks/issues/120#issuecomment-1047192531

If I use [this](https://github.com/elishacloud/Logging) logging library and try to `` iniReader.Read*`` anything, it just doesn't do anything. `` iniReader.Write*`` works though, which is odd.
Any idea what could cause this?

**Comment by ThirteenAG** [comment]
Hmm, I'm not sure. Maybe it's related to operator overloading in logging? Have you tried to debug this?

>  iniReader.Write*

probably because it has `bool useparser = false` by default, which means something breaks in [ini_parser.hpp](https://github.com/ThirteenAG/IniReader/blob/master/ini_parser.hpp) when Logging is included.

**Comment by nipkownix** [comment]
> Have you tried to debug this?

Haven't had the time to look too much into it yet, but I'll do it as soon as possible and report back if I find anything.

**Comment by nipkownix** [comment]
Seems this line:
https://github.com/ThirteenAG/IniReader/blob/85c2845b9dda0fa1f36612f8476d432dab1730d7/ini_parser.hpp#L310

Goes to here instead of just reading the ``file`` into ``ss``:

https://github.com/elishacloud/Logging/blob/master/Logging.h#L441

And then ``read_file`` reads no lines, resulting in ``data`` being empty and nothing being parsed. Hmm.

**Comment by ThirteenAG** [comment]
Probably something to fix in logging then, since it overloads those operators.

**Comment by nipkownix** [comment]
Yeah. Thanks for taking a look.
